apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-koi5
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-koi5@sha256:e058e6e42155f0777d5f0ae07d42a6c4ed5e614874dd40723c1182df4fc35391
        name: my-nodejs
        resources: {}
status: {}
